# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6zCEeASUtCrs2jA9hHY1rNlm9S79gXx

**Handwritten Character Recognition**
"""

!pip install cupy
!pip install idx2numpy
from google.colab import drive
drive.mount('/content/drive') #Mount Google Drive to access files
import numpy as np #NumPy is a library for numerical operations in Python
import cupy as cp  # #CuPy is a GPU-accelerated library for numerical operations
import idx2numpy #Import idx2numpy for converting IDX file format to NumPy array
import random #Import random for generating random numbers

# Load the dataset using idx2numpy
drive_path = '/content/drive/MyDrive/'
train_images_path = drive_path + 'train-images.idx3-ubyte'
train_images = idx2numpy.convert_from_file(train_images_path)
train_labels_path = drive_path + 'train-labels.idx1-ubyte'
train_labels = idx2numpy.convert_from_file(train_labels_path)
test_images_path = drive_path + 't10k-images.idx3-ubyte'
test_images = idx2numpy.convert_from_file(test_images_path)
test_labels_path = drive_path + 't10k-labels.idx1-ubyte'
test_labels = idx2numpy.convert_from_file(test_labels_path)

use_gpu = cp.cuda.is_available()
if use_gpu:
    print("GPU")

## Convert and normalize training and test images using CuPy
train_images = cp.asarray(train_images.reshape(train_images.shape[0], -1) / 255.0)
test_images = cp.asarray(test_images.reshape(test_images.shape[0], -1) / 255.0)


# Defining ctivation functions and their derivatives
def tanh(x):
    return cp.tanh(x)

def relu(x):
    return cp.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + cp.exp(-x))

def mean_squared_error_derivative(predicted, target):
    return predicted - target

def sigmoid_derivative(x):
    return x * (1 - x)

def relu_derivative(x):
    return cp.where(x > 0, 1, 0)

def tanh_derivative(x):
    return 1 - cp.tanh(x)**2

# Neural Network class definition
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, activation_function):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        # Initialize weights and biases
        self.weights_input_hidden = cp.random.uniform(-0.01, 0.01, (input_size, hidden_size))

        self.bias_hidden = cp.zeros((1, hidden_size))
        self.weights_hidden_output = cp.random.uniform(-0.01, 0.01, (hidden_size, output_size))

        self.bias_output = cp.zeros((1, output_size))
        self.activation_function = activation_function
    # Forward pass through the neural network
    def forward(self, x):
        self.hidden_input = cp.dot(x, self.weights_input_hidden) + self.bias_hidden
        if self.activation_function == 'case1':
            self.hidden_output = tanh(self.hidden_input)
        elif self.activation_function == 'case2':
            self.hidden_output = relu(self.hidden_input)
        self.output = cp.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output


        if self.activation_function == 'case1':
            self.output = tanh(self.output)
        elif self.activation_function == 'case2':
            self.output = sigmoid(self.output)

        return self.output

# Hyperparameters
learning_rate = 0.01
num_epochs = 50
batch_size = 50


input_size = 784
hidden_size = 300
output_size = 10

hidden_sizes = [300, 500, 1000]
learning_rates = [0.01, 0.05, 0.09]
activation_functions = ['case1', 'case2']
results = []

# Hyperparameter grid search
for learning_rate in learning_rates:
    for hidden_size in hidden_sizes:
        for activation_function in activation_functions:
          # Create an instance of the NeuralNetwork class
            model = NeuralNetwork(input_size, hidden_size, output_size, activation_function)
            for epoch in range(num_epochs):
                total_loss = 0
                # Iterate over training data in batches
                for i in range(0, len(train_images), batch_size):
                    batch_images = train_images[i:i+batch_size]
                    batch_labels = train_labels[i:i+batch_size]

                    # Forward pass
                    outputs = model.forward(batch_images)
                    # Calculate loss and derivatives based on activation function
                    if model.activation_function == 'case1':
                        desired_outputs = cp.array([[-1.0] * 10] * len(batch_labels), dtype=cp.float32)
                        for idx, label in enumerate(batch_labels):
                            desired_outputs[idx, label] = 1.0


                        mse = cp.mean(cp.square(desired_outputs - outputs))
                        total_loss += mse

                        error = mean_squared_error_derivative(outputs, desired_outputs)
                        error = error / len(batch_labels)
                        delta_output = error * tanh_derivative(outputs)

                        error_hidden = cp.dot(delta_output, model.weights_hidden_output.T)
                        delta_hidden = error_hidden * tanh_derivative(model.hidden_output)


                    elif model.activation_function == 'case2':
                        desired_outputs = cp.array([[0] * 10] * len(batch_labels), dtype=cp.float32)
                        for idx, label in enumerate(batch_labels):
                            desired_outputs[idx, label] = 1.0


                        mse = cp.mean(cp.square(desired_outputs - outputs))
                        total_loss += mse

                        error = mean_squared_error_derivative(outputs, desired_outputs)
                        error = error / len(batch_labels)
                        delta_output = error * sigmoid_derivative(outputs)

                        error_hidden = cp.dot(delta_output, model.weights_hidden_output.T)
                        delta_hidden = error_hidden * relu_derivative(model.hidden_output)

                    # Update weights and biases using gradient descent
                    model.weights_hidden_output -= learning_rate * cp.dot(model.hidden_output.T, delta_output)
                    model.bias_output -= learning_rate * cp.sum(delta_output, axis=0, keepdims=True)

                    model.weights_input_hidden -= learning_rate * cp.dot(batch_images.T, delta_hidden)
                    model.bias_hidden -= learning_rate * cp.sum(delta_hidden, axis=0, keepdims=True)

                # Evaluate the test accuracy after each epoch
                correct = 0
                total = 0
                for i in range(0, len(test_images), batch_size):
                    batch_images = test_images[i:i+batch_size]
                    batch_labels = test_labels[i:i+batch_size]
                    outputs = model.forward(batch_images)
                    predicted = cp.argmax(outputs, axis=1)
                    correct += cp.sum(predicted == cp.asarray(batch_labels))
                    total += len(batch_labels)

            test_accuracy = (correct / total) * 100
            # Print results for each combination of hyperparameters
            print({
                'Number of Neurons': hidden_size,
                'Learning Rate': learning_rate,
                'Activation': activation_function,
                'Epoch': epoch + 1,
                'Test Accuracy': test_accuracy
            })