# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lstVffhs12sB3-vNB9EPh3HxwDUxLL5E

**Mini Project 2**
"""

# Installing necessary libraries
!pip install cupy
!pip install h5py

# Mounting Google Drive to access files
from google.colab import drive
drive.mount('/content/drive')

# Importing necessary libraries
import cupy as cp  # Importing Cupy for GPU-accelerated computations
import h5py  # Importing h5py for handling H5 file format

# Setting up file paths
file_path = "/content/drive/MyDrive/"
Mini_Project = file_path + 'Assignment 2 dataset.h5'  # Path to the H5 dataset file

# Loading data from the H5 file
with h5py.File(Mini_Project, 'r') as data:
    # Accessing dataset components
    trXX, trYY, tstXX, tstYY = data['trX'], data['trY'], data['tstX'], data['tstY']

    # Extracting data into arrays
    trX = trXX[:]  # Training data features
    trY = trYY[:]  # Training data labels
    tstX = tstXX[:]  # Test data features
    tstY = tstYY[:]  # Test data labels

# Hyperparameters
# These variables define various settings for the neural network training process.
learning_rates = [0.05, 0.1]
N_values = [50, 100]
batch_sizes = [10, 30]
epochs = 50

"""**Activation functions**"""

# Activation functions
# Functions used to introduce non-linearity into the network's layers.
def tanh(x):
    return cp.tanh(x)

def sigmoid(x):
    return 1 / (1 + cp.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def softmax(x):
    # Softmax function used in the output layer to normalize the output into probability distributions.
    exp_x = cp.exp(x - cp.max(x, axis=1, keepdims=True))
    return exp_x / cp.sum(exp_x, axis=1, keepdims=True)

"""**Loss functions and derivatives**

"""

# Loss functions and derivatives
# These functions compute the discrepancy between predicted and actual values during training.
def cross_entropy_loss(y, y_hat):
    epsilon = 1e-15  # A small constant to avoid numerical instability in logarithm
    y_hat = cp.clip(y_hat, epsilon, 1 - epsilon)  # Clip values to avoid log(0) or log(1)
    return -cp.mean(y * cp.log(y_hat) + (1 - y) * cp.log(1 - y_hat))

def cross_entropy_derivative(y, y_hat):
    epsilon = 1e-15
    y_hat = cp.clip(y_hat, epsilon, 1 - epsilon)
    d_loss = -(y / y_hat - (1 - y) / (1 - y_hat))
    return d_loss / len(y)

"""**Initialize weights and biases**"""

# Function to initialize weights and biases for the neural network layers
def initialize_parameters(N):
    cp.random.seed(42)  # Set a seed for reproducibility
    WIH = cp.random.uniform(-0.1, 0.1, size=(N, 3 + 1))  # Weight matrix for input to hidden layer
    WHH = cp.random.uniform(-0.1, 0.1, size=(N, N))  # Weight matrix for hidden to hidden layer
    WHO = cp.random.uniform(-0.1, 0.1, size=(6, N + 1))  # Weight matrix for hidden to output layer
    return WIH, WHH, WHO

def top_k_accuracy(predictions, labels, k=1):
        top_k_predictions = cp.argsort(predictions, axis=1)[:, -k:][:, ::-1]
        correct_predictions = cp.argmax(labels, axis=1)

        correct_top_k = cp.sum(top_k_predictions == correct_predictions[:, cp.newaxis], axis=1)
        top_k_acc = cp.mean(correct_top_k > 0)

        return top_k_acc

"""**Forward pass**"""

# Function to perform the forward pass through the neural network
def forward_pass(inputs, WIH, WHH, WHO):
    hidden_states = [cp.zeros((inputs.shape[0], WIH.shape[0]))]  # Initial hidden state

    for t in range(inputs.shape[1]):
        x_t = cp.hstack([inputs[:, t, :], cp.ones((inputs.shape[0], 1))])  # Concatenate input with bias
        h_t = tanh(cp.dot(x_t, WIH.T) + cp.dot(hidden_states[-1], WHH.T))  # Calculate hidden state
        hidden_states.append(h_t)  # Store hidden state for each time step

    output = sigmoid(cp.dot(cp.hstack([hidden_states[-1], cp.ones((inputs.shape[0], 1))]), WHO.T))  # Calculate output
    return hidden_states, output

"""**Backward Pass**"""

def backward_pass(inputs, labels, hidden_states, output, WIH, WHH, WHO, learning_rate):
    # Calculate error as the derivative of the cross-entropy loss
    error = cross_entropy_derivative(output, labels)
    error /= len(labels)  # Normalize error by the number of samples
    dWHO = cp.dot(error.T, cp.hstack([hidden_states[-1], cp.ones((inputs.shape[0], 1))]))  # Gradient for WHO

    # Initialize gradients for WHH and WIH
    dWHH = cp.zeros_like(WHH)
    dWIH = cp.zeros_like(WIH)

    # Calculate delta_output as the derivative of the sigmoid activation for the output layer
    delta_output = error * output * (1 - output)

    # Calculate delta_hidden as the derivative of the tanh activation for the hidden layer
    delta_hidden = cp.dot(delta_output, WHO[:, :-1]) * (1 - hidden_states[-1] ** 2)

    # Loop over time steps backward to compute gradients
    for t in range(inputs.shape[1], inputs.shape[1] - 10, -1):
        x_t = cp.hstack([inputs[:, t - 1, :], cp.ones((inputs.shape[0], 1))])


        # Compute gradients for WHH and WIH at each time step
        dWHH_t = cp.dot(delta_hidden.T, hidden_states[t - 1])  # Gradient for WHH at time step t
        dWIH_t = cp.dot(delta_hidden.T, x_t)  # Gradient for WIH at time step t

        # Accumulate gradients for each time step
        dWHH += dWHH_t
        dWIH += dWIH_t

        # Update delta_hidden for the previous time step using the recurrent weights WHH
        delta_hidden = cp.dot(delta_hidden, WHH) * (1 - hidden_states[t - 1] ** 2)

    # Normalize gradients by sequence length
    dWHH /= inputs.shape[1]
    dWIH /= inputs.shape[1]

    # Update weights and biases using the accumulated gradients and learning rate
    WHO -= learning_rate * dWHO
    WHH -= learning_rate * dWHH
    WIH -= learning_rate * dWIH

    return WIH, WHH, WHO  # Return updated weights and biases

"""**Training loop, Validation error calculation & Testing**"""

# Training loop
for learning_rate in learning_rates: # Iterate over different learning rates
    for N in N_values: # Iterate over different N values
        for batch_size in batch_sizes: # Iterate over different batch sizes
            WIH, WHH, WHO = initialize_parameters(N)  # Initialize weights and biases


            best_val_error = float('inf')
            patience = 5
# Training loop for multiple epochs
            for epoch in range(epochs): # Iterate over epochs
                total_loss = 0  # Initialize total loss for each epoch
                for i in range(0, trX.shape[0], batch_size):
                    batch_inputs = trX[i:i + batch_size]
                    batch_labels = cp.asarray(trY[i:i + batch_size])
                  # Perform the forward pass to obtain predictions
                    hidden_states, output = forward_pass(batch_inputs, WIH, WHH, WHO)

                    # Calculate cross-entropy loss with tanh and sigmoid activations
                    total_loss += cp.sum(-batch_labels * cp.log(output + 1e-10))

                    # Backward pass
                    WIH, WHH, WHO = backward_pass(batch_inputs, batch_labels, hidden_states, output, WIH, WHH, WHO, learning_rate)

                # Validation error (not part of the training loop)
                val_error = 0
                for j in range(0, 3000, 50):
                    val_inputs = trX[j:j + 50]
                    val_labels = cp.asarray(trY[j:j + 50])
                    _, val_output = forward_pass(val_inputs, WIH, WHH, WHO)
                    val_error += cp.sum(-val_labels * cp.log(val_output + 1e-10))
                # Early stopping check
                if val_error < best_val_error:
                  best_val_error = val_error
                  patience_counter = 0
                else:
                  patience_counter += 1
                if patience_counter >= patience:
                   print(f"Early stopping at epoch {epoch + 1} as validation error did not improve.")
                   break
                # Print validation error for the current epoch

                average_loss = total_loss / (trX.shape[0] / batch_size)
                print(f"Epoch {epoch + 1}/{epochs}, Validation Error: {val_error / 3000}")

            # Testing
            _, test_output = forward_pass(tstX, WIH, WHH, WHO)
            test_predictions = cp.argmax(test_output, axis=1)
            # print(test_predictions,tstY)
            test_accuracy = cp.mean(test_predictions + 1 == cp.argmax(cp.asarray(tstY), axis=1))


            print(f"Learning Rate: {learning_rate}, N: {N}, Batch Size: {batch_size}")
            print("Test Accuracy:", test_accuracy)
            print()
            # Calculate Top-k accuracy
            for k in range(1, 4):  # Calculate Top-1, Top-2, and Top-3 accuracy
              top_k_acc = top_k_accuracy(test_output, cp.asarray(tstY), k)
              print(f"Top-{k} Accuracy:", top_k_acc)
            print()